### ISSUE TITLE
READMEのRequirementに依存gemの記述は不要

### ISSUE THREAD

**Issue by tbpgr** [hkdnet/komonjo#2]
個別のgemとかは記載不要です。
READMEでこれを書くとGemfileと重複管理になっていまうので。

**Comment by tbpgr** [comment]
![寿司ゆき:ok](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/03.png)

**Comment by hkdnet** [comment]
![寿司ゆき:thanks](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/04.png)
