### ISSUE TITLE
ディレクトリ名に関して

### ISSUE THREAD

**Issue by tbpgr** [hkdnet/komonjo#3]
複数形の方が良いです。

* connection => connections
* gateway => gateways

他も同様。

**Comment by hkdnet** [comment]
テストのところの修正漏れそうだった:moyai:
`libs = %w(connections gateways mocks models)`

**Comment by tbpgr** [comment]
![LGTM](https://pbs.twimg.com/media/CHLUT1WU0AIpqpM.png)
