### ISSUE TITLE
Pull Request 後のブランチ

### ISSUE THREAD

**Issue by tbpgr** [hkdnet/komonjo#4]
本流にマージし終わったブランチは削除したほうがよいです。
（Pull Requestの画面から削除可能）

https://github.com/hkdnet/komonjo/pull/1
（Pull Requestした本人だけ上記画面の最下部にブランチの削除ボタンが表示されているはず）

**Comment by hkdnet** [comment]
deleted!
![寿司ゆき:sigh](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/06.png)

**Comment by tbpgr** [comment]
![ミサワ](http://livedoor.4.blogimg.jp/jigokuno_misawa/imgs/e/0/e0798703.gif)

**Comment by tbpgr** [comment]
煽るテスト
