### ISSUE TITLE
htmlエスケープされたままになる

### ISSUE THREAD

**Issue by hkdnet** [hkdnet/komonjo#8]
例
> &amp;gt;フリーザ様

Rubyのやりかたを調べてデコードすればおkっぽい

**Comment by hkdnet** [comment]
Issue内部でエスケープされたものを書くために `&amp;gt;` とか書いた

**Comment by hkdnet** [comment]
冷静になってみるとcodeで書けばよかったじゃん

**Comment by tbpgr** [comment]
<script>alert(1);</script>
test

**Comment by hkdnet** [comment]
preタグだから微妙に違和感があるんだけど……まあいいか
